### PR TITLE
Setup on the proto-BOSH server

### PR DESCRIPTION
**Pull request by 7hunderbird**
Working through what gets setup on the _proto-BOSH_ server, this PR begins the process of adding some diagrams that will help give people a "you are here" of what they are working on.  Also add headers to sections to help make the transitions between topics smooth / clear.

### CODE REVIEW

**Comment by xiujiao** [comment]
@7hunderbird  We may want to rename Vault related things, the thing we called `proto-Vault` is actually a dev version of `photo-vault`, the thing we name `Vault` is the real `proto-Vault` in the same environment with `prop-Bosh`. So `porto-vault` should be `dev-porto-Vault`, real `Vault` can leave as current name Vault (like shield and concourse, they are in proto,but they are just called Shield not proto-shiled) or we can name it `photo-Vault` (As bosh called `porto-bosh`

**Comment by xiujiao** [comment]
@7hunderbird I am not sure change site name from `aww` to `infra` is a good idea. Because when we have other infrastructure like vsphere in the same deployment repo, this site naming will confuse us.

**Comment by xiujiao** [comment]
@7hunderbird Maybe change `ops` to `deployments` is better since inside this folder will be things like `cf-deployments`, `bosh-deployments`. What do you think?

**Comment by 7hunderbird** [comment]
> @7hunderbird We may want to rename Vault related things, the thing we called proto-Vault is actually a dev version of photo-vault, the thing we name Vault is the real proto-Vault in the same environment with prop-Bosh. So porto-vault should be dev-porto-Vault, real Vault can leave as current name Vault (like shield and concourse, they are in proto, but they are just called Shield not proto-shiled) or we can name it photo-Vault (As bosh called porto-bosh).

In the first site we have a bosh, vault, shield, bolo, concourse.

The reason we call the first bosh "proto-BOSH" is because of how we're using it to help create new bosh directors in other site/env that a client asks for.

The `vault server -dev` that is run to help stand up the proto-BOSH, and then later helps deploy Vault to the first site.  We can call it whatever we want.

* dev-Vault
* pre-Vault
* proto-Vault

> @7hunderbird I am not sure change site name from `aws` to `infra` is a good idea. Because when we have other infrastructure like vsphere in the same deployment repo, this site naming will confuse us.

I wanted to [set a standard](https://github.com/starkandwayne/codex/blob/9874e137e50386e6d093942a639103cb1f4dd86b/aws.md#infrastructure--proto---site--environment) in this draft that the site / env was `infra` / `proto` for the entire first site we setup.

I feel there does need to be a distinction between the two Vaults, because we have more than one as we do the first site's setup.

The other services/software that get setup don't need to combine the environment into the title, because they will be running the software as a top level, globally unique, management layer that manages each sub-site that is created from it.

> @7hunderbird Maybe change ops to deployments is better since inside this folder will be things like cf-deployments, bosh-deployments. What do you think?

In the PR the change is from [ops to deploy](https://github.com/starkandwayne/codex/blob/9874e137e50386e6d093942a639103cb1f4dd86b/aws.md#generate-bosh-deploy) is currently what is there. 

We could do either `deploys` or `deployments`.  I thought the singular looked fine, but there will be more than one in that folder, so I can understand making it plural.

**Comment by xiujiao** [comment]
In TOC.md, line 93, we may want to use Proto-Bosh to keep consistent with other parts
In aws.md,
 line 510, you mean dev-Vault?
 line 555, set up a `deployments` server
  line 584 ,`/deployments/docs/bosh-deployments/aws` is not consistent with the genesis command
  line 908 and 909, should be `deployments/bosh-deployments/infra-aws/proto`
  line 938, should be `secret/infra-aws/proto/`, you may want to check if all the other vault related paths is changed from `aws` to `infra-aws` to be consistent
  line 1157, in `bosh vms aws-dev-Vault`, the deployment name here `aws-dev-Vault` is set through genesis by `site-environmet-rootdeployment`, since we are changing site to `infra-aws`, the deployment name will automatically be `infra-aws-proto-vault`. 
  line 1248 , naming for vault is confusing since we name `dev-vault` as `proto`, and vault in proto environment as ops. But if we want to change this, we need to go through the whole doc to keep the naming consistent and less confusing .

The last, in the diagrams, porto-vault should be  dev-Vault

**Comment by 7hunderbird** [comment]
Here's some of the inconsistencies, because each of these guides were previously written by different people, at different times.

`ops` was 

* a safe target
* folder name to store deployments
* line 993 described as the `proto-BOSH` environment name

Yet upon further research the environment that `proto-BOSH` and all the deployments that get created from it should be the `proto` environment.

In order to do this we need to: 

* change the first safe target from `proto` to `init`.  
* Update the other safe targets from `ops` to `proto`.
* find any services that are using an `ops` environment and update them to `proto`.

Then the `ops` folder can just be the working operator's folder of deployments and miscellaneous and not a confusing psuedo environment.

We'd need to fix up a couple of other things.

I'd like to propose we use the AWS region as the `genesis` site.

* Anything named `infra-aws` would become `us-west-2`.
* Things that remain named `aws` that is for a site, becomes a region `us-west-2`

Before this becomes a megalith PR (too late) I'm not planning on making all of the above changes below the initial area of my PR's scope which was approximately line 600.  Any changes below there were most likely global find and replace, if inaccurate we can get them in a future pass with this as a style guide.

**Comment by xiujiao** [comment]
@7hunderbird From line 1286 to 1312, the path for the secrets should be something like `secret/us-west-2/proto/shield/webui`
line 1315 should be proto instead of ops

I believe there are still places we missed for consistency. If we have someone follow the doc from the beginning and verify  everything will be nice:)

**Comment by 7hunderbird** [comment]
If we can, let's fix that in the next PR.  We've already struck gold with figuring out a good consistent name structure.

**Pull request merged**
