### PR TITLE
CF Database Networks

### PR DESCRIPTION
**Pull request by frodenas**
This is a proposal to add CF Databases (CCDB & UAADB, either hosted in RDS or using the MySQL release) to the Network Plan, and the updated Terraform configuration according to the new Network Plan.

/cc @7hunderbird, @geofffranks, @jhunt, @bodymindarts

### CODE REVIEW

**Comment by frodenas** [comment]
I'm not yet sure that 14 available hosts, even per AZ, will be enough if in the future we plan to deploy the MySQL release (for those IaaS that does not have a hosted MySQL service). Thoughts?

**Comment by frodenas** [comment]
Now it includes the creation of RDS Clusters. By default, they are turned off. If you want to enable them, you need to set these properties:

```
variable "aws_rds_dev_enabled"     { default = 0 } # Set to 1 to create the DEV RDS cluster
variable "aws_rds_staging_enabled" { default = 0 } # Set to 1 to create the STAGING RDS cluster
variable "aws_rds_prod_enabled"    { default = 0 } # Set to 1 to create the PROD RDS cluster
```

**Comment by 7hunderbird** [comment]
@frodenas can you update your PR to be zero based index on the network names?  Perhaps just merging with upstream changes will fix first?

**Comment by frodenas** [comment]
@7hunderbird Done

**Comment by 7hunderbird** [comment]
looking really good, is this ready to 🚢  or are you still working on it?

**Comment by frodenas** [comment]
Yes, it's ready to merge.

**Comment by 7hunderbird** [comment]
Awesome stuff :shipit:

**Pull request merged**
