### PR TITLE
fix staging subnet naming

### PR DESCRIPTION
**Pull request by xiujiao**

### CODE REVIEW

**Comment by jhunt** [comment]
Does this affect other, non-staging networks?

**Comment by xiujiao** [comment]
@jhunt I do not think so.  I just added missing index for staging subnet names

**Comment by jhunt** [comment]
You sure?

```
$ grep infra terraform/aws/aws.tf | grep tags
  tags { Name = "${var.aws_vpc_name}-global-infra-1" }
  tags { Name = "${var.aws_vpc_name}-global-infra-2" }
  tags { Name = "${var.aws_vpc_name}-global-infra-3" }
  tags { Name = "${var.aws_vpc_name}-dev-infra" }
  tags { Name = "${var.aws_vpc_name}-dev-infra" }
  tags { Name = "${var.aws_vpc_name}-dev-infra" }
  tags { Name = "${var.aws_vpc_name}-staging-infra" }
  tags { Name = "${var.aws_vpc_name}-staging-infra" }
  tags { Name = "${var.aws_vpc_name}-staging-infra" }
  tags { Name = "${var.aws_vpc_name}-prod-infra" }
  tags { Name = "${var.aws_vpc_name}-prod-infra" }
  tags { Name = "${var.aws_vpc_name}-prod-infra" }
```

**Comment by xiujiao** [comment]
Oh, I misunderstood you. I thought you are asking "does the staging changes I made effects other non-stagings?"
Do you mean it should be 
```
tags { Name = "${var.aws_vpc_name}-global-infra-1" }
  tags { Name = "${var.aws_vpc_name}-global-infra-2" }
  tags { Name = "${var.aws_vpc_name}-global-infra-3" }
  tags { Name = "${var.aws_vpc_name}-dev-infra-1" }
  tags { Name = "${var.aws_vpc_name}-dev-infra-2" }
  tags { Name = "${var.aws_vpc_name}-dev-infra-3" }
  tags { Name = "${var.aws_vpc_name}-staging-infra-1" }
  tags { Name = "${var.aws_vpc_name}-staging-infra-2" }
  tags { Name = "${var.aws_vpc_name}-staging-infra-3" }
  tags { Name = "${var.aws_vpc_name}-prod-infra-1" }
  tags { Name = "${var.aws_vpc_name}-prod-infra-2" }
  tags { Name = "${var.aws_vpc_name}-prod-infra-3" }
```

**Comment by jhunt** [comment]
Seems to me if we index staging, we ought to index all of them.

**Comment by xiujiao** [comment]
Yeah, we indexed all other ones except staging, dev and prod. Now they are all consistent.Thanks for catching it. Changes for prod, dev are pushed

**Pull request merged**
