### PR TITLE
Indexing

### PR DESCRIPTION
**Pull request by wayneeseguin**
Adjusted to 0-based indexing for naming.

### CODE REVIEW

**Comment by 7hunderbird** [comment]
Looks good. :shipit:

**Comment by jhunt** [comment]
Why?

**Comment by xiujiao** [comment]
Nerds count from 0 ?

**Comment by jhunt** [comment]
Memory access counts from 0.  The previous indexing was consistent with the third octet in the network range it represented, 10.4.1.0/24 was global-infra-1, 10.4.2.0/24 was 2, etc.

Is there a pressing reason to move to 0-indexing for the names of the networks?

**Comment by jhunt** [comment]
If we do want to keep the 0-indexing, we should probably update the names in the network plan to match.

**Pull request merged**
