### PR TITLE
Break up aws.md so we can use its content to template other platforms

### PR DESCRIPTION
**Pull request by jrbudnack**
Hi folks,

I took a stab at breaking up the AWS walkthrough into common vs. explicit content.  The python script should be parameterized more, but I want to get your eyes on this first.  

The "walkthrough" folder contains the common "snippets", plus a subfolder that represents the AWS specifics, which are contained in 2 files:

parameters.json - Contains parameters to substitute into the common snippets, such as the name of the service (AWS), the site name (us-west-2), stemcell name, version, etc.

walkthrough.md - This is the "source" document, which includes the snippet files 

The idea here is you can just copy the AWS directory and use it as a starting point to see the order in which the snippets are included and the where the platform specifics fit in (most of it has to do with cloud_properties and networking).  This way, at least for the common content, we won't have to go through the headache of altering the same paragraph x number of times when edits are called for.  Also, half the document is written for you, and they all flow the same.

When you clone this branch, run "python bin/build_walkthrough.py" to see this in action.  IT WILL OVERWRITE aws.md - but when you do "git diff", you will find that not much has changed, other than some additional errors I found while going through the doc.

Please let me know what you think - we on the CBTS project are hoping to use this as a jumping off point as soon as possible so we can generate Openstack documentation for the client.

Thanks!
Jeremy

### CODE REVIEW

**Comment by jrbudnack** [comment]
The walkthrough.md file uses "spruce-ish" syntax, via 2 directives - they're pretty much just string substitution:

(( include_file <filename> )) is replaced by the contents of <filename>
(( include_parameter <paramname> )) is replaced by the parameter referenced in parameters.json

**Comment by xiujiao** [comment]
@jrbudnack I like your idea a lot! I made two improvements based on your work and comments about parameterizing: 
1) The walkthrough path is now retrieved from the current working directory instead of being hard coded; 
2) We can now specify what type of file (eg. aws.md, openstack.md, google.md, etc.) we want to generate from the command line. 
I did not add a test to see if the file type argument matches infrastructure types we support though.  I did not code in pytyon before, therefore a code review is appreciated.

**Comment by norman-abramovitz** [comment]
If I remember correclty:  It centered around the discussion are we writing for the author or are we writing for the reader.  The author wants pieces while the reader wants continuous flow.  If someone makes changes to the 'common' code then they should test across all platforms.  If a common section becomes specific then there is more work.  Just because an environment was updated with a newer release, it does not mean the other environments are also ready for new release as well.  @tbird was the lead at the time, so he made the final decision.  Waiting for Tyler to weigh in on this discussion.

**Comment by jhunt** [comment]
@7hunderbird can you please weigh in on this so we can move forward?  I'd like to merge this...

**Comment by 7hunderbird** [comment]
@jrbudnack walked me through this and we came up with the following:

* Add a file timestamp check, that would ensure the aws.md file could only be written to if the date was older than the sourcefiles.
* Communicate things to people in the README.md (How to work with and generate from source)
* Send a message to discussions announcing the change.

**Comment by jhunt** [comment]
FWIW, `make` does this timestamp check automatically.

**Comment by jrbudnack** [comment]
I implemented this differently, as I discovered that timestamp can vary widely depending on git's shenanigans, and therefore can't really be trusted to determine if the product was manually edited.  Instead, I take more of a Genesis-like approach and have a .build directory to ensure we can build the previous walkthrough, compare it with the current version - THEN if it all checks out, build the new generated version and then copy the component files into .build.  That way, if someone changes the walkthrough directly, the walkthrough will not agree with the build files that supposedly built it and will trigger the script to not generate the new one.

Once this PR is accepted and merged, I will submit one more direct edit to"aws.md" to "prime the pump" so it agrees with the build files (i also had some minor spelling / clarifying changes) - and yes, I will make sure I include the changes recently submitted by @jhunt and @djvdorp.

**Comment by 7hunderbird** [comment]
I wonder if we add the `.build` folder to the `.gitignore` file?

**Comment by jrbudnack** [comment]
Actually no - we need the build files to be in the repo too, so when people actually pull down the new version of aws.md, they also receive the files that were used to build it.  That way, they have 2 sets of build files:  1 that they actually edit, and the "hidden set" that is used by the script to first build "what was" to ensure that nobody edited aws.md raw, and "what will be" which will be used to generate the new aws.md, and will replace the .build files after it is built.  We do something similar with .site and .global in Genesis.

**Comment by 7hunderbird** [comment]
Awesome, thanks for that clarification! :shipit:

**Pull request merged**
